/*
 * Code for Programmable Interval Timer (PIT).
 *
 */
#define PIT_CHANNEL_0               0x40
#define PIT_COMMAND_REGISTER        0x43
#define PIT_FREQUENCY               1193182 /* 1.193182 MHz */

#define PIT_SELECT_CHANNEL_0        0b00000000
#define PIT_ACCESS_MODE_LO_HI_BYTE  0b00110000
#define PIT_OPERATING_MODE_RATE_GENERATOR 0b00000100
#define PIT_BINARY_MODE             0b00000000

void kprintln(char *);

void timer_callback(struct Registers *r)
{
    kprintln("from timer_callback");
}

/* IRQ0 is generated by the rising edge of the Channel 0 */
void init_pit(u32 freq)
{
    u8 mode = PIT_SELECT_CHANNEL_0 | PIT_ACCESS_MODE_LO_HI_BYTE | PIT_OPERATING_MODE_RATE_GENERATOR | PIT_BINARY_MODE;

    u32 freq_divider = PIT_FREQUENCY / freq;

    outb(PIT_COMMAND_REGISTER, mode);   // Set the mode for channel 0
    outb(PIT_CHANNEL_0, (u8)(freq_divider & 0xFF));
    outb(PIT_CHANNEL_0, (u8)((freq_divider >> 8) & 0xFF));

    // add_irq_handler(IRQ_0, timer_callback);
}
